name: GoPal UI

on:
  push:
    branches:
      - main

concurrency:
  group: gopalui-deployment-group
  cancel-in-progress: false

jobs:
  build-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GoPalUI Repo repository
        uses: actions/checkout@v2
        with:
          repository: congpham234/GoPalUI
          ref: main

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Code
        run: npm run build

  trigger-cdk-repo-workflow:
    runs-on: ubuntu-latest
    needs: build-code
    steps:
      - name: Trigger workflow in CDK repository
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          "https://api.github.com/repos/congpham234/GoPalUICDK/dispatches" \
          -d "{\"event_type\": \"trigger-workflow\", \"client_payload\": {\"COMMIT_MESSAGE\": \"${{ github.event.head_commit.message }}\"}}"
