name: GoPal UI

on:
  push:
    branches:
      - main

concurrency:
  group: gopalui-deployment-group
  cancel-in-progress: false

jobs:
  build-and-deploy-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GoPalUI Repo repository
        uses: actions/checkout@v2
        with:
          repository: congpham234/GoPalUI
          ref: main

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Code
        run: npm run build

  send-discord-notification:
    runs-on: ubuntu-latest
    needs: [build-and-deploy-code]
    if: always()
    steps:
      - name: Send Discord Notification
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ contains(needs.*.result, 'failure') && 'Failure' || 'Success' }}
          title: "${{ github.event.head_commit.message }}"
          image: ${{ contains(needs.*.result, 'failure') && secrets.EMBED_IMAGE_FAILURE || secrets.EMBED_IMAGE_SUCCESS }}
          color: ${{ contains(needs.*.result, 'failure') && '0xFF0000' || '0x00FF00' }}
          url: "https://github.com/congpham234/GoPalBackendCDK"
          username: ${{ contains(needs.*.result, 'failure') && 'Ur MOM' || 'Kilala' }}
          avatar_url: ${{ contains(needs.*.result, 'failure') && secrets.EMBED_IMAGE_FAILURE || secrets.EMBED_IMAGE_SUCCESS }}
